name: Bug Report
description: Create a report to help us improve Astra Userbot
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or Terminal Output
      description: Please paste any relevant logs, errors, or tracebacks here.
      render: shell
  - type: input
    id: version
    attributes:
      label: Astra Userbot Version
      description: What version are you running? (e.g., v0.0.1b)
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform / Deployment
      description: Where are you running the bot?
      options:
        - Windows Native
        - macOS / Linux Native
        - Docker
        - Railway
        - Heroku
        - Render
        - VPS (Ubuntu/Debian)
    validations:
      required: true
